#!/bin/sh

BLAKE3=deps/BLAKE3/c

mkdir -p .obj/blake3
clang -o .obj/blake3/blake3.o -c $BLAKE3/blake3.c
clang -o .obj/blake3/blake3_dispatch.o -c $BLAKE3/blake3_dispatch.c
clang -o .obj/blake3/blake3_portable.o -c $BLAKE3/blake3_portable.c
clang -msse2 -o .obj/blake3/blake3_sse2.o -c $BLAKE3/blake3_sse2.c
clang -msse4.1 -o .obj/blake3/blake3_sse41.o -c $BLAKE3/blake3_sse41.c
clang -mavx2 -o .obj/blake3/blake3_avx2.o -c $BLAKE3/blake3_avx2.c
clang -mavx512f -mavx512vl -o .obj/blake3/blake3_avx512.o -c $BLAKE3/blake3_avx512.c

CXXFLAGS="-Isrc -Ideps/cereal/include -Ideps/CLI11/include -I$BLAKE3 -Wall -Wfatal-errors -O3 --std=c++17 -g -fstandalone-debug"

clang++ -o rkr $CXXFLAGS src/*/*.cc .obj/blake3/*.o -lstdc++fs -lfmt

clang -O3 -o rkr-launch launch/launch.c
