#!/bin/sh

/usr/lib/gcc/x86_64-linux-gnu/9/cc1 -v -imultiarch x86_64-linux-gnu hello.c -dumpbase hello.no_ws.c -mtune=generic -march=x86-64 -auxbase hello.no_ws -O3 -Wall -version -fasynchronous-unwind-tables -fstack-protector-strong -Wformat-security -fstack-clash-protection -fcf-protection -o hello.s 2>/dev/null
cp hello.s output.s