name: check
on: [push, pull_request]
jobs:
  check:
    runs-on:
      - ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-22.04-arm64]
        mode: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make clang gcc python3-cram file graphviz
          sudo update-alternatives --install /usr/bin/cram cram /usr/bin/cram3 100

      - name: Build
        run: make ${{ matrix.mode }}
      
      - name: Test
        run: make test-${{ matrix.mode }}
      
      - name: Self-Build
        run: ${{ matrix.mode }}/bin/rkr --show
      
      - name: Test Self-Build
        run: PATH=$PWD/self-build/bin:$PATH scripts/runtests.py
