name: check
on: [push, pull_request]
jobs:
  check:
    runs-on:
      - linux
      - ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [x64, ARM64]
        mode: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Build
        run: make ${{ matrix.mode }}
      
      - name: Test
        run: make test-${{ matrix.mode }}
      
      - name: Self-Build
        run: ${{ matrix.mode }}/bin/rkr --show
      
      - name: Test Self-Build
        run: PATH=$PWD/self-build/bin:$PATH scripts/runtests.py
