name: Run Tests

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: git submodule init
      - run: git submodule update
      - run: make
      - run: make test
