name: test
on: [push, pull_request]
jobs:
  run:
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    strategy:
      matrix:
        mode: [debug, release]
        #arch: [x64, arm64]
        arch: [x64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make ${{ matrix.mode }} -j2
      - run: make test-${{ matrix.mode }}
