name: test
on: push
jobs:
  run:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        mode: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make ${{ matrix.mode }}
      - run: make test-${{ matrix.mode }}
