name: Run Tests

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test